CREATE DATABASE mintyBD;
USE mintyBD;

CREATE TABLE usuarios(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(40),
email VARCHAR(40),
senha VARCHAR(20)
);

CREATE USER user_crud IDENTIFIED BY 'Sptech#2026';
GRANT INSERT, SELECT, UPDATE, DELETE ON mintyDB.* TO user_crud;
FLUSH PRIVILEGES;

